# These requires must be loaded in order of dependency:
require 'opal/phaser/game_objects/events'
require 'opal/phaser/game_objects/sprite'
require 'opal/phaser/game_objects/tile_sprite'
require 'opal/phaser/game_objects/text'
require 'opal/phaser/game_objects/image'
require 'opal/phaser/game_objects/bitmap_data'
require 'opal/phaser/game_objects/button'
require 'opal/phaser/game_objects/filter'
require 'opal/phaser/game_objects/rope'
require 'opal/phaser/game_objects/game_object_factory'
