require 'opal/phaser/core/state'
require 'opal/phaser/core/game'
require 'opal/phaser/core/physics'
require 'opal/phaser/core/game_object_factory'
require 'opal/phaser/core/sprite'
require 'opal/phaser/core/image'
require 'opal/phaser/core/group'