require 'native'

require 'opal/phaser/core/state'
require 'opal/phaser/core/physics'
require 'opal/phaser/core/group'
require 'opal/phaser/core/animation'
require 'opal/phaser/core/animation_manager'
require 'opal/phaser/core/sprite'
require 'opal/phaser/core/image'
require 'opal/phaser/core/text'
require 'opal/phaser/core/cache'
require 'opal/phaser/core/game_object_factory'
require 'opal/phaser/core/game'